name: Lint HTML

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run HTMLHint
        uses: Cyb3r-Jak3/htmlhint-action@v1.1.0
        with:
          htmlhint-config: ".htmlhintrc"  # Optional, if you want to customize rules